INSERT INTO `mazatlanpassport`.`stores` (
  `id`,
  `name`,
  `slogan`,
  `description`,
  `email`,
  `phone`,
  `website`,
  `address`,
  `maps_slug`,
  `profile_image`,
  `cover_image`,
  `facebook_id`,
  `instagram_id`,
  `twitter_id`,
  `reservation`,
  `admin_key`
) VALUES (
  (UUID_TO_BIN('c92b27b7-a64c-42f4-9673-dd6e64cd4ab3')),
  'Todos Santos',
  'Mariscos Bar',
  'El Lugar Donde el Sabor, La Fiesta y La diversión crean una Magia que seguramente te hará Muy Feliz!',
  'todosantosoficial@gmail.com',
  526691121322,
  'Avenida de la Marina, De La Alameda 800, Sanchez Celis, 82120.',
  'sCdfjjfN5WjrAneQ6'
  'todossantosmariscos.com',
  '/public/images/stores/todos-santos/todos-santos-mariscos-bar-profile-cover.webp',
  '/public/images/stores/todos-santos/todos-santos-mariscos-bar-profile-image.webp',
  'todosantosmariscosoficial',
  'todossantosmariscos',
  'Todossantosbar',
  1,
  1
);